// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpfvcfnmvoovkqrjipbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZnZjZm5tdm9vdmtxcmppcGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDQwNDUsImV4cCI6MjA2ODY4MDA0NX0.TZqW0UuY92CVogsz628QJrdvPn8SWDskbzs4BAXyhR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});